#!/bin/bash
#This script simplifies non-interactive docker run commands by loading 
# environment variables from a file and running the container with the
# specified options.

# Usage: docker exec container_name runops [options] [command]
# Options: (none)

# Load environment variables from file using /load_env.sh
source /load_env.sh /vcpkg
# run the command 
exec "$@"


