/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'ML_Test.balanced+CM3' 
 * Target:  'balanced+CM3' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM3.h"

/* ARM::CMSIS-View:Event Recorder&Semihosting@1.5.2 */
#define RTE_CMSIS_View_EventRecorder
        #define RTE_CMSIS_View_EventRecorder_DAP
        #define RTE_CMSIS_View_EventRecorder_Semihosting


#endif /* RTE_COMPONENTS_H */
