/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'ML_Test.size+CM7' 
 * Target:  'size+CM7' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM7.h"

/* ARM::CMSIS-View:Event Recorder&Semihosting@1.5.2 */
#define RTE_CMSIS_View_EventRecorder
        #define RTE_CMSIS_View_EventRecorder_DAP
        #define RTE_CMSIS_View_EventRecorder_Semihosting
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.7.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */


#endif /* RTE_COMPONENTS_H */
