/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'ML_Model.size+CM4_FP' 
 * Target:  'size+CM4_FP' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* tensorflow::Machine Learning:TensorFlow:Kernel&CMSIS-NN@1.22.8 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
