/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'ML_Test.speed+CM55_Ethos' 
 * Target:  'speed+CM55_Ethos' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Arm::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.22.8 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55


#endif /* PRE_INCLUDE_GLOBAL_H */
