/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'ML_Test.speed+CM55_Ethos' 
 * Target:  'speed+CM55_Ethos' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE300MPS3.h"

/* ARM::CMSIS-View:Event Recorder&Semihosting@1.5.2 */
#define RTE_CMSIS_View_EventRecorder
        #define RTE_CMSIS_View_EventRecorder_DAP
        #define RTE_CMSIS_View_EventRecorder_Semihosting
/* Arm::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.22.8 */
#define RTE_ETHOS_U_CORE_DRIVER
/* tensorflow::Data Exchange:Serialization:flatbuffers&tensorflow@1.22.8 */
#define RTE_DataExchange_Serialization_flatbuffers     /* flatbuffers */
/* tensorflow::Machine Learning:TensorFlow:Testing@1.22.8 */
#define RTE_ML_TF_LITE     /* TF */


#endif /* RTE_COMPONENTS_H */
