# This YAML file is used to build and run an ML project on Arm Virtual Hardware FVP
# It contains a job that runs tests on a Ubuntu machine using a custom Docker image

name: ML Project MLEK Keyword Spotting - Build and Run on Arm Virtual Hardware FVP

on:
  # Trigger the workflow when a workflow run is completed
  workflow_run:
    workflows: ["Licensed Docker Image - Build and Push"]
    types:
      - completed
  # Trigger the workflow manually
  workflow_dispatch:

jobs:
  run_test:
    runs-on: ubuntu-latest
    container:
      # Use the custom Docker image with the necessary tools and dependencies
      image: ghcr.io/arm-software/avh-mlops/arm-mlops-docker-licensed:latest
      credentials:
        # Set the Docker image credentials using the actor and a GitHub token
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        # Check out the repository containing the ML project
        uses: actions/checkout@v2

      - name: Set permissions for working directory __w
        # Set permissions for the working directory to avoid permission errors
        run: chmod 777 -R /__w

      - name: Build Model and Test for Cortex-M4 with AC6 (balanced) / Corstone-300 for Community Edition
        run: |
             if [ -z "${{ secrets.ARM_UBL_LICENSE_IDENTIFIER }}" ]; then
                su - arm_mlops_docker -c "/home/arm_mlops_docker/cmsis-toolbox-linux-amd64/bin/cbuild /__w/AVH-MLOps/AVH-MLOps/mlek-kws/MLOps.csolution.yml --packs --active CM55_Ethos --toolchain AC6"
              else
                su - arm_mlops_docker -c "/home/arm_mlops_docker/cmsis-toolbox-linux-amd64/bin/cbuild /__w/AVH-MLOps/AVH-MLOps/mlek-kws/MLOps.csolution.yml --packs --active CM4 --toolchain AC6"
              fi

      - name: Execute Test Project on Arm Virtual Hardware FVP
        run: |
            if [ -z "${{ secrets.ARM_UBL_LICENSE_IDENTIFIER }}" ]; then
             su - arm_mlops_docker -c "/home/arm_mlops_docker/avh-fvp-11.29.27/bin/FVP_Corstone_SSE-300_Ethos-U55 -f /__w/AVH-MLOps/AVH-MLOps/mlek-kws/Target/CM55_Ethos/fvp_config.txt /__w/AVH-MLOps/AVH-MLOps/mlek-kws/out/ML_Test/CM55_Ethos/balanced/ML_Test.axf -C ethosu.num_macs=256 -Q 1 --simlimit 12"
            else
             su - arm_mlops_docker -c "/home/arm_mlops_docker/avh-fvp-11.29.27/bin/FVP_MPS2_Cortex-M4 -f /__w/AVH-MLOps/AVH-MLOps/TFLmicrospeech/Target/CM4/fvp_config.txt /__w/AVH-MLOps/AVH-MLOps/mlek-kws/out/ML_Test/CM4/balanced/ML_Test.axf -Q 1 --simlimit 12"
            fi

      - name: Get timings from Event Recorder Log
        run: |
             su - arm_mlops_docker -c "/home/arm_mlops_docker/cmsis-toolbox-linux-amd64/bin/eventlist -s ./EventRecorder.log"
