name: Build and Push Licensed Docker Image 

on:
  workflow_run:
    workflows: ["Build and Push Base Docker Image"]
    types:
      - completed

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Format repo slug
        id: repo_slug
        run: |
          echo "REPO_SLUG=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
 
      - name: Pull Base Docker image
        run: docker pull ghcr.io/${{ env.REPO_SLUG }}/arm-mlops-docker-base:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker_licensed
          push: true
          tags: ghcr.io/${{ env.REPO_SLUG }}/arm-mlops-docker-licensed:latest
